# Generated by Django 2.2.2 on 2019-06-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='student Name', max_length=100, null=True)),
                ('book_name', models.CharField(blank=True, help_text='Book Name', max_length=100, null=True)),
                ('book_issue', models.DateField(blank=True, null=True, verbose_name='Book Issue')),
                ('book_return', models.DateField(blank=True, null=True, verbose_name='Book return')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
