# Generated by Django 2.2.2 on 2019-06-20 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='customer',
            field=models.ForeignKey(help_text='<button type="button" class="btn btn-outline-primary">issue</button><button type="button" class="btn btn-outline-secondary">return</button>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Customer'),
        ),
    ]
